%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/allanemmanuelumali/Desktop/SEA COVID Cross-Correlation/Sigdisc Final Dataset 1.xlsx
%    Worksheet: Sheet2
%
% Auto-generated by MATLAB on 04-Feb-2022 21:22:57

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = "Sheet2";
opts.DataRange = "A2:M1081";

% Specify column names and types
opts.VariableNames = ["Date", "PhNewCases", "PhNewCasesPct", "PhNewDeath", "PhNewDeathPct", "ChinaNewCases", "ChinaNewCasesPct", "ChinaNewDeath", "ChinaNewDeathPct", "IndiaNewCases", "IndiaNewCasesPct", "IndiaNewDeath", "IndiaNewDeathPct"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Date", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Date", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["PhNewCases", "PhNewCasesPct", "PhNewDeath", "PhNewDeathPct", "ChinaNewCases", "ChinaNewCasesPct", "ChinaNewDeath", "ChinaNewDeathPct", "IndiaNewCases", "IndiaNewCasesPct", "IndiaNewDeath", "IndiaNewDeathPct"], "FillValue", 0);

% Import the data
tbl = readtable("/Users/allanemmanuelumali/Desktop/SEA COVID Cross-Correlation/Sigdisc Final Dataset 1.xlsx", opts, "UseExcel", false);

%% Convert to output type
Date = tbl.Date;
PhNewCases = tbl.PhNewCases;
PhNewCasesPct = tbl.PhNewCasesPct;
PhNewDeath = tbl.PhNewDeath;
PhNewDeathPct = tbl.PhNewDeathPct;
ChinaNewCases = tbl.ChinaNewCases;
ChinaNewCasesPct = tbl.ChinaNewCasesPct;
ChinaNewDeath = tbl.ChinaNewDeath;
ChinaNewDeathPct = tbl.ChinaNewDeathPct;
IndiaNewCases = tbl.IndiaNewCases;
IndiaNewCasesPct = tbl.IndiaNewCasesPct;
IndiaNewDeath = tbl.IndiaNewDeath;
IndiaNewDeathPct = tbl.IndiaNewDeathPct;

%% Clear temporary variables
clear opts tbl

%% Initialization
%clear all;
clc;
close all;

%%  Since Start of COVID; summary plot
figure('Name','Plot Summary of COVID Cases');
subplot(3,3,1); plot(ChinaNewCases); title('China New Cases');
subplot(3,3,2); plot(PhNewCases); title('Ph New Cases');
subplot(3,3,3); plot(IndiaNewCases); title('India New Cases');

subplot(3,3,4); plot(ChinaNewCasesPct); title('% Change');
subplot(3,3,5); plot(PhNewCasesPct); title('% Change');
subplot(3,3,6); plot(IndiaNewCasesPct); title('% Change');

%% Cross Correlations
[C1, lag1] = xcorr(PhNewCasesPct,ChinaNewCasesPct);
[C2, lag2] = xcorr(PhNewCasesPct,IndiaNewCasesPct);
[C3, lag3] = xcorr(ChinaNewCasesPct,IndiaNewCasesPct);

figure('Name','PH vs. China New Cases Cross Correlation');
C1_New = C1./max(abs(C1(:)));
plot(lag1,C1_New);

figure('Name','PH vs. India New Cases Cross Correlation');
C2_New = C2./max(abs(C2(:)));
plot(lag2,C2_New);

figure('Name','China vs. India New Cases Cross Correlation');
C3_New = C3./max(abs(C3(:)));
plot(lag3,C3_New);

%% 2021 to Current
PhNewCases2021 = PhNewCases(347:end,:);
PhNewCasesPct2021 = PhNewCasesPct(347:end,:);

ChinaNewCases2021 = ChinaNewCases(347:end,:);
ChinaNewCasesPct2021 = ChinaNewCasesPct(347:end,:);

IndiaNewCases2021 = IndiaNewCases(347:end,:);
IndiaNewCasesPct2021 = IndiaNewCasesPct(347:end,:);

%Cross Correlations
[C4, lag4] = xcorr(PhNewCasesPct2021,ChinaNewCasesPct2021);
[C5, lag5] = xcorr(PhNewCasesPct2021,IndiaNewCasesPct2021);
[C6, lag6] = xcorr(ChinaNewCasesPct2021,IndiaNewCasesPct2021);

figure('Name','PH vs. China New Cases Cross Correlation 2021');
C4_New = C4./max(abs(C4(:)));
plot(lag4,C4_New);

figure('Name','PH vs. India New Cases Cross Correlation 2021');
C5_New = C5./max(abs(C5(:)));
plot(lag5,C5_New);

figure('Name','China vs. India New Cases Cross Correlation 2021');
C6_New = C6./max(abs(C6(:)));
plot(lag6,C6_New);

%% Table Comparisons

figure('Name','PH vs. China Raw 2021 New Cases Pct');
plot(ChinaNewCasesPct2021); hold on; plot(PhNewCasesPct2021,'g'); hold off; 
legend('China','Ph');

figure('Name','PH vs. India Raw 2021 New Cases Pct');
plot(IndiaNewCasesPct2021); hold on; plot(PhNewCasesPct2021,'g'); hold off; 
legend('India','Ph');

figure('Name','China vs. India Raw 2021 New Cases Pct');
plot(ChinaNewCasesPct2021); hold on; plot(IndiaNewCasesPct2021,'g'); hold off; 
legend('China','India');

%% Extra Visualization
figure('Name', 'China vs. Ph New Cases Pct');
plot(ChinaNewCasesPct); hold on; plot(PhNewCasesPct); hold off;
legend('China','Ph');

figure('Name', 'India vs. Ph New Cases Pct');
plot(IndiaNewCasesPct); hold on; plot(PhNewCasesPct); hold off;
legend('India','Ph');

figure('Name', 'China vs. India New Cases Pct');
plot(ChinaNewCasesPct); hold on; plot(IndiaNewCasesPct); hold off;
legend('China','India');
%% Checking and Verifying through Linear Regression
[rho1,pval1] = corr(PhNewCasesPct2021,ChinaNewCasesPct2021,'type','Spearman');
% [rho2,pval2] = corr(PhNewCasesPct2021,IndiaNewCasesPct2021,'type','Spearman');
% [rho3,pval3] = corr(ChinaNewCasesPct2021,IndiaNewCasesPct2021,'type','Spearman');

% PH lead of 54 days
PhTest = PhNewCasesPct(55:end,:)
ChinaTest = ChinaNewCasesPct(1:end-54,:);
[rhotest,pvaltest] = corr(PhTest,ChinaTest,'type','Pearson');
[C4test, lag4test] = xcorr(PhTest,ChinaTest);
figure(999); plot(lag4test,C4test);
figure(1000); plot(ChinaTest); hold on; plot(PhTest,'g'); hold off;

